### ISSUE TITLE
Dead Kernel

### ISSUE THREAD

**Issue by utsavnanda** [lse-st445/lectures#7]
Just got an issue with the R task on Assignment 1. When I open the file in Jupyter, I keep getting a 'Dead Kernel' message. I've tried restarting the kernel and I've looked online for possible solutions too but nothing seems to have worked.

I seem to recall that a few people had the same issue during the seminar. Did anyone manage to solve it?

Thanks,

Utsav

**Comment by christineyuen** [comment]
Hi Utsav,

As I have not encountered the same problem with my computer, I do not know why this problem occurs and I am not sure if I can solve it. But if you still have the issue and you are around today or the coming Monday, I can try to see if I can help. My office is at COL 5.02. Thank you.

Christine

**Comment by utsavnanda** [comment]
What time are you free today? I've got a lecture from 1pm-3pm but I can come straight after that if you're free?

Thanks,
Utsav

**Comment by zcuaan** [comment]
I have been having the same issue; I still haven't been able to resolve it.

**Comment by christineyuen** [comment]
Anytime from 2pm to 6pm should be fine. 

Christine

**Comment by kbenoit** [comment]
@christineyuen @chmue @amatsuo Would love if someone figures this one out, since in preparing my lectures for tomorrow I am experiencing the same annoying issue on my office iMac. R kernel starts but then dies before interpreting my code.

**Comment by kbenoit** [comment]
@milenavt any ideas?

**Comment by milenavt** [comment]
I've never had this issue with Python so I'm not sure I can help.

**Comment by amatsuo** [comment]
Obviously, the issue is caused by `R` installed by anaconda. So the solution is to uninstall anaconda R, install r-kernel from normal R. 

I believe this is related to this:
https://github.com/ContinuumIO/anaconda-issues/issues/999

**Steps**
1. Uninstall anaconda R. From terminal, enter`conda uninstall r-base` (Follow steps, remove all)
2. (If you don't have system `R`, install it from https://www.r-project.org/)
3. Open a new terminal window (Don't skip this. You need to re-read bash env)
4. Open `R` in terminal (type `R` then hit enter)
4. Install R kernel in terminal
     ```r
       install.packages('devtools')
       devtools::install_github('IRkernel/IRkernel')
       IRkernel::installspec() 
    ```
5. Start `jupyter notebook`

This solved the issue on Ken's iMac.

**Comment by utsavnanda** [comment]
Thank you so much! It solved the issue on my laptop too.

**Comment by zcuaan** [comment]
Mine works now too, thank you!
